# Generated by Django 4.1.3 on 2022-12-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'db_table': 'activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип активностей',
                'verbose_name_plural': 'Типы активностей',
                'db_table': 'activity_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('receiving_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('cost_used', models.IntegerField()),
                ('comment', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sum', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счеты',
                'db_table': 'cheques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('next_date', models.DateField()),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('definition', models.CharField(max_length=200)),
                ('start_cost', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тип занятий',
                'verbose_name_plural': 'Типы занятий',
                'db_table': 'class_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fcs', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientsContacts',
            fields=[
                # ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контактные данные клиентов',
                'verbose_name_plural': 'Контактные данные клиентов',
                'db_table': 'clients_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientsGroup',
            fields=[
                ('is_leader', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
                'db_table': 'clients_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientStatuses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
                'db_table': 'client_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Тип клиента',
                'verbose_name_plural': 'Типы клиентов',
                'db_table': 'client_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('ban_on_spam', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsMedia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('media', models.IntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('is_main', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Соц сети контактов',
                'verbose_name_plural': 'Соц сети контактов',
                'db_table': 'contacts_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип контактов',
                'verbose_name_plural': 'Типы контактов',
                'db_table': 'contacts_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Фидбек',
                'verbose_name_plural': 'Фидбек',
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'db_table': 'quests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LenAppMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('date_sent', models.DateField()),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LenAppMessagetemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=200)),
                ('template_str', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'message_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('site', models.CharField(max_length=30)),
                ('is_legal', models.BooleanField()),
                ('use_phone', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Соц сети',
                'verbose_name_plural': 'Соц сети',
                'db_table': 'media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaidTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
                'db_table': 'paid_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sum_paid', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип фото',
                'verbose_name_plural': 'Типы фото',
                'db_table': 'photo_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Фото изделия',
                'verbose_name_plural': 'Фото изделий',
                'db_table': 'product_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=400)),
                ('cost', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_cost', models.IntegerField()),
                ('definition', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы фото',
                'db_table': 'product_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadyStates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Состояние готовности',
                'verbose_name_plural': 'Состояния готовности',
                'db_table': 'ready_states',
                'managed': False,
            },
        ),
    ]
