# Generated by Django 4.1.3 on 2022-12-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
                'db_table': 'paid_types',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PaidTypes',
        ),
        migrations.AlterModelTable(
            name='guests',
            table='guests',
        ),
    ]
