# Generated by Django 4.1.3 on 2022-12-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0002_paidtype_delete_paidtypes_alter_guests_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypes',
            options={'managed': False, 'verbose_name': 'Тип изделия', 'verbose_name_plural': 'Типы изделий'},
        ),
    ]
