# Generated by Django 4.1.3 on 2023-01-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0003_alter_producttypes_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientsGroup',
        ),
    ]
