# Generated by Django 4.1.3 on 2023-01-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len', '0006_userdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
