# Generated by Django 4.1.3 on 2023-01-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('len', '0007_delete_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMonthGuests',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=200)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
            ],
            options={
                'db_table': 'last_month_guests',
                'managed': False,
            },
        ),
    ]
